CREATE TABLE FINTECH_DB.PUBLIC.FTC_TRANSACTIONS AS 
WITH TRANSACTIONS AS (
    SELECT * FROM STG_TRANSACTIONS
),
MERCHANTS AS (
    SELECT * FROM STG_MERCHANTS
),
DISPUTES AS (
    SELECT * FROM STG_DISPUTES
),
DEVICES AS (
    SELECT * FROM STG_DEVICES
),
CUSTOMERS AS (
    SELECT * FROM STG_CUSTOMERS
),
CARDS AS (
    SELECT * FROM STG_CARDS
),
ACCOUNTS AS (
    SELECT * FROM STG_ACCOUNTS
),
JOIN_DATA AS (
    SELECT
        T.TRANSACTION_ID,
        T.CUSTOMER_ID,
        T.ACCOUNT_ID,
        T.DEVICE_ID,
        T.TRANSACTION_TS,
        T.AMOUNT,
        T.CURRENCY,
        T.AMOUNT_GBP,
        T.TRANSACTION_TYPE,
        T.CHANNEL,
        T.MERCHANT_CATEGORY,
        T.MERCHANT_CITY,
        T.MERCHANT_COUNTRY,
        T.PAYMENT_METHOD,
        T.AUTHORIZATION_STATUS,
        T.SETTLEMENT_STATUS,
        T.FRAUD_SCORE,
        T.IS_INTERNATIONAL,
        T.DECLINED_REASON,

        DI.DISPUTE_REASON,
        DI.DISPUTE_STATUS,
        DI.OPENED_DATE,
        DI.CLOSED_DATE,
        DI.DISPUTED_AMOUNT,
        DI.RESOLUTION_AMOUNT,

        D.DEVICE_TYPE,
        D.OS_NAME,
        D.FIRST_SEEN_TS,
        D.LAST_SEEN_TS,
        D.JAILBROKEN,
        D.VPN_USAGE_FLAG,

        C.FULL_NAME,
        C.EMAIL,
        C.PHONE,
        C.DATE_OF_BIRTH,
        C.SIGNUP_DATE,
        C.CITY,
        C.COUNTRY AS CUSTOMER_COUNTRY,
        C.OCCUPATION,
        C.ANNUAL_INCOME,
        C.KYC_STATUS,
        C.MARKETING_OPT_IN,
        C.RISK_BAND,
        C.SEGMENT,
        C.EMPLOYER_NAME,

        CA.CARD_NETWORK,
        CA.CARD_TYPE,
        CA.ISSUE_DATE,
        CA.EXPIRY_DATE,
        CA.CARD_STATUS,
        CA.COUNTRY_ISSUED,

        A.ACC_OPENED_DATE,
        A.ACCOUNT_STATUS,
        A.CURRENT_BALANCE,
        A.CREDIT_LIMIT,
        A.CURRENCY AS ACC_CURRENCY,
        A.ACC_TYPE

    FROM TRANSACTIONS T
    LEFT JOIN MERCHANTS M
        ON T.MERCHANT_CITY = M.CITY
    LEFT JOIN DISPUTES DI
        ON T.TRANSACTION_ID = DI.TRANSACTION_ID
    LEFT JOIN DEVICES D
        ON T.DEVICE_ID = D.DEVICE_ID
    LEFT JOIN CUSTOMERS C
        ON T.CUSTOMER_ID = C.CUSTOMER_ID
    LEFT JOIN CARDS CA
        ON T.ACCOUNT_ID = CA.ACCOUNT_ID
    LEFT JOIN ACCOUNTS A
        ON T.ACCOUNT_ID = A.ACCOUNT_ID
)

SELECT *
FROM JOIN_DATA;

select * from ftc_transactions;