SELECT DISPUTE_ID,TRANSACTION_ID,CUSTOMER_ID FROM RAW_DISPUTES
WHERE DISPUTE_ID IS NULL OR TRANSACTION_ID IS NULL OR CUSTOMER_ID IS NULL;

SELECT DISTINCT dispute_reason  FROM RAW_DISPUTES;

-- corrected dispute status 
SELECT DISTINCT LOWER(DISPUTE_STATUS)  FROM RAW_DISPUTES;

SELECT 
COALESCE(
TRY_TO_DATE(OPENED_DATE,'YYYY-MM-DD'),
TRY_TO_DATE(OPENED_DATE,'YYYY/MM/DD'),
TRY_TO_DATE(OPENED_DATE,'DD-MM-YYYY'),
TRY_TO_DATE(OPENED_DATE,'DD/MM/YYYY'),
TRY_TO_DATE(OPENED_DATE,'DD-MON-YYYY'),
TRY_TO_DATE(OPENED_DATE,'DD/MON/YYYY')
) AS OPENED_DATE,
COALESCE(
TRY_TO_DATE(CLOSED_DATE,'YYYY-MM-DD'),
TRY_TO_DATE(CLOSED_DATE,'YYYY/MM/DD'),
TRY_TO_DATE(CLOSED_DATE,'DD-MM-YYYY'),
TRY_TO_DATE(CLOSED_DATE,'DD/MM/YYYY'),
TRY_TO_DATE(CLOSED_DATE,'DD-MON-YYYY'),
TRY_TO_DATE(CLOSED_DATE,'DD/MON/YYYY')
) AS CLOSED_DATE
FROM RAW_DISPUTES
;

-- CORRECTED DISPUTE AMMOUNT
SELECT TRY_CAST(REPLACE(DISPUTED_AMOUNT,'£','') AS FLOAT),
DISPUTED_AMOUNT
FROM RAW_DISPUTES;

-- CORRECTED DISPUTE AMMOUNT
SELECT TRY_CAST(REPLACE(RESOLUTION_AMOUNT,'£','') AS FLOAT),
RESOLUTION_AMOUNT
FROM RAW_DISPUTES;


