SELECT * FROM RAW_CUSTOMERS;

SELECT CUSTOMER_ID 
FROM RAW_CUSTOMERS
WHERE CUSTOMER_ID IS NULL;

--CORRECTED FULL NAME ✅
SELECT INITCAP(TRIM(FULL_NAME)) FROM RAW_CUSTOMERS;

SELECT FULL_NAME 
FROM RAW_CUSTOMERS
WHERE FULL_NAME IS NULL;

-- CORRECTING EMAIIL ✅
SELECT 
    REPLACE(LOWER(TRIM(EMAIL)),' ','') 
FROM RAW_CUSTOMERS;

SELECT EMAIL FROM RAW_CUSTOMERS
WHERE EMAIL NOT LIKE '%@%.%.%' AND EMAIL NOT LIKE '%@%.%' ;

-- CORRECTING PHONE ✅
SELECT LPAD(LPAD(PHONE,10,0),12,4) FROM RAW_CUSTOMERS;

SELECT 
    COALESCE(
        TRY_TO_DATE(DATE_OF_BIRTH,'DD-MM-YYYY'),
        TRY_TO_DATE(DATE_OF_BIRTH,'DD/MM/YYYY'),
        TRY_TO_DATE(DATE_OF_BIRTH,'YYYY-MM-DD'),
        TRY_TO_DATE(DATE_OF_BIRTH,'YYYY/MM/DD')
        ) AS DATE_OF_BIRTH,
    COALESCE(
        TRY_TO_DATE(SIGNUP_DATE,'DD-MM-YYYY'),
        TRY_TO_DATE(SIGNUP_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(SIGNUP_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(SIGNUP_DATE,'YYYY/MM/DD')
        ) AS SIGNUP_DATE
FROM RAW_CUSTOMERS;

SELECT
    DISTINCT OCCUPATION
    FROM RAW_CUSTOMERS;

--CORRECTED ANNUAL_INCOME ✅
SELECT
TRY_CAST(REPLACE(REPLACE(TRIM(ANNUAL_INCOME),',',''),'£','') AS FLOAT)
FROM RAW_CUSTOMERS;

--CORRECTED KYC_STATUS ✅
SELECT DISTINCT LOWER(KYC_STATUS) FROM RAW_CUSTOMERS;

--CORRECTED MARKETING OPT IN ✅
SELECT DISTINCT 
CASE 
    WHEN MARKETING_OPT_IN IN ('Y','Yes','true') THEN 'YES'
    WHEN MARKETING_OPT_IN IN ('N','No','false') THEN 'NO'
    ELSE 'NO'
END AS MARKETING_OPT_IN
FROM RAW_CUSTOMERS;

SELECT DISTINCT
CASE 
    WHEN RISK_BAND IN ('Low','LOW') THEN 'Low'
    WHEN RISK_BAND IN ('med','Medium') THEN 'Medium'
    WHEN RISK_BAND IN ('High') THEN 'High'
    ELSE NULL
END AS RISK_BAND
FROM RAW_CUSTOMERS;

SELECT DISTINCT INITCAP(SEGMENT) FROM RAW_CUSTOMERS;
SELECT DISTINCT INITCAP(EMPLOYER_NAME) FROM RAW_CUSTOMERS;