    CREATE TABLE STG_ACCOUNTS AS
    SELECT
        ACCOUNT_ID,
        CUSTOMER_ID,
        PRODUCT_TYPE,
        COALESCE(
        TRY_TO_DATE(OPENED_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(OPENED_DATE,'YYYY/MM/DD'),
        TRY_TO_DATE(OPENED_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(OPENED_DATE,'DD-MM-YYYY')
        ) AS ACC_OPENED_DATE,
        LOWER(TRIM(ACCOUNT_STATUS)) AS ACCOUNT_STATUS,
        TRY_CAST(REPLACE(CURRENT_BALANCE,',','') AS FLOAT) AS CURRENT_BALANCE,
        CREDIT_LIMIT,
        CURRENCY,
        LPAD(TO_VARCHAR(IBAN_LAST4),4,0) AS IBAN_LAST4,
        SORT_CODE,
        CASE
            WHEN IS_JOINT_ACCOUNT = TRUE THEN 'JOINT'
            WHEN IS_JOINT_ACCOUNT = FALSE THEN 'SINGLE'
            ELSE 'UNKNOWN'
        END AS ACC_TYPE
    FROM FINTECH_DB.PUBLIC.RAW_ACCOUNTS
    WHERE CURRENT_BALANCE IS NOT NULL
    ;


