CREATE TABLE STG_DEVICES AS
SELECT 
     DEVICE_ID,
     CUSTOMER_ID_PRIMARY,
     DEVICE_TYPE,
     OS_NAME,
     APP_VERSION,
     TRY_TO_TIMESTAMP(FIRST_SEEN_TS) AS FIRST_SEEN_TS,
     TRY_TO_TIMESTAMP(LAST_SEEN_TS) AS LAST_SEEN_TS,
     CASE
        WHEN JAILBROKEN IN ('Y','Yes') THEN 'YES'
        WHEN JAILBROKEN IN ('N','No') THEN 'NO'
        ELSE 'UNKNOWN'
     END AS JAILBROKEN,
    CASE
        WHEN VPN_USAGE_FLAG IN ('Y','Yes') THEN 'YES'
        WHEN VPN_USAGE_FLAG IN ('N','No') THEN 'NO'
        ELSE 'UNKNOWN'
    END AS VPN_USAGE_FLAG,
    HOME_COUNTRY_CODE
FROM RAW_DEVICES;

