---SAMPLE DATA
SELECT * FROM RAW_ACCOUNTS;

---CHECKING INVALID CUST & ACC ID
SELECT ACCOUNT_ID,CUSTOMER_ID 
FROM RAW_ACCOUNTS
WHERE ACCOUNT_ID NOT LIKE 'A%' OR CUSTOMER_ID NOT LIKE 'C%'
;

---CHECKING DUPLICATE ACC ID
SELECT ACCOUNT_ID,COUNT(ACCOUNT_ID)
FROM RAW_ACCOUNTS
GROUP BY ACCOUNT_ID
HAVING COUNT(ACCOUNT_ID)>1
;

---CHECKING INVALID OR MISSPPELLS,TYPO IN PRODUCT TYPES
SELECT PRODUCT_TYPE,COUNT(PRODUCT_TYPE) AS COUNT
FROM RAW_ACCOUNTS
GROUP BY PRODUCT_TYPE;

--CHECKING DATES
SELECT OPENED_DATE FROM RAW_ACCOUNTS;

-- DATE FORMATES

SELECT DISTINCT OPENED_DATE FROM RAW_ACCOUNTS;

SELECT COUNT(*) AS TOTAL,COUNT(TRY_TO_DATE(OPENED_DATE)) AS VALID_DATES FROM RAW_ACCOUNTS;

SELECT OPENED_DATE FROM RAW_ACCOUNTS
WHERE OPENED_DATE IS NULL;

-- CORRECTING DATES ✅
SELECT 
    COALESCE(
        TRY_TO_DATE(OPENED_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(OPENED_DATE,'YYYY/MM/DD'),
        TRY_TO_DATE(OPENED_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(OPENED_DATE,'DD-MM-YYYY')
        )
FROM RAW_ACCOUNTS
WHERE COALESCE(
        TRY_TO_DATE(OPENED_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(OPENED_DATE,'YYYY/MM/DD'),
        TRY_TO_DATE(OPENED_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(OPENED_DATE,'DD-MM-YYYY')
        ) IS NULL
;


SELECT DISTINCT ACCOUNT_STATUS FROM RAW_ACCOUNTS;

-- CORRECTING THE CASETYPES TO SMALLERCASE ✅ 
SELECT DISTINCT LOWER(TRIM(ACCOUNT_STATUS)) FROM RAW_ACCOUNTS;

-- REMOVE NULL VALUES ✅ 
SELECT CURRENT_BALANCE FROM RAW_ACCOUNTS
WHERE CURRENT_BALANCE IS NULL ;

--CORRECTING DATATYPE ✅
SELECT TRY_CAST(REPLACE(CURRENT_BALANCE,',','') AS FLOAT)  FROM RAW_ACCOUNTS;

-- CHECKING NULLS
SELECT CURRENT_BALANCE FROM RAW_ACCOUNTS
WHERE TRY_CAST(REPLACE(CURRENT_BALANCE,',','') AS FLOAT) IS NULL ;

--CHECKING MISSPLACING CREDIT LIMIT OUT OF CREDIT ACC
SELECT DISTINCT CREDIT_LIMIT FROM RAW_ACCOUNTS
WHERE PRODUCT_TYPE NOT LIKE 'Credit';

SELECT DISTINCT CURRENCY FROM RAW_ACCOUNTS;

-- CORRECTING THE DATATYPE AND MAKING IBAN 3DIGIT TO 4 BY ADDING 0 IN FRONT✅
SELECT LPAD(TO_VARCHAR(IBAN_LAST4),4,0) FROM RAW_ACCOUNTS;

-- CHECKING SHORTCODE
SELECT SORT_CODE FROM RAW_ACCOUNTS
WHERE SORT_CODE NOT LIKE '__-__-__';

SELECT IS_JOINT_ACCOUNT FROM RAW_ACCOUNTS;


--MAKE NULL TO UNKNOWN ACC ✅
SELECT
    CASE
        WHEN IS_JOINT_ACCOUNT = TRUE THEN 'JOINT'
        WHEN IS_JOINT_ACCOUNT = FALSE THEN 'SINGLE'
        ELSE 'UNKNOWN'
    END AS ACC_TYPE
FROM RAW_ACCOUNTS
GROUP BY ACC_TYPE;


