SELECT MERCHANT_ID 
FROM RAW_MERCHANTS
WHERE MERCHANT_ID IS NULL OR MERCHANT_ID NOT LIKE 'M%'
;

SELECT DISTINCT REPLACE(MERCHANT_NAME,'*','') 
FROM RAW_MERCHANTS
;

SELECT DISTINCT MERCHANT_CATEGORY 
FROM RAW_MERCHANTS
;

SELECT DISTINCT CITY 
FROM RAW_MERCHANTS
;

SELECT DISTINCT COUNTRY 
FROM RAW_MERCHANTS
;

SELECT COALESCE(
    TRY_TO_DATE(ONBOARDING_DATE,'YYYY-MM-DD'),
    TRY_TO_DATE(ONBOARDING_DATE,'YYYY/MM/DD'),
    TRY_TO_DATE(ONBOARDING_DATE,'DD-MM-YYYY'),
    TRY_TO_DATE(ONBOARDING_DATE,'DD/MM/YYYY')
)
FROM RAW_MERCHANTS
WHERE 
 COALESCE(
    TRY_TO_DATE(ONBOARDING_DATE,'YYYY-MM-DD'),
    TRY_TO_DATE(ONBOARDING_DATE,'YYYY/MM/DD'),
    TRY_TO_DATE(ONBOARDING_DATE,'DD-MM-YYYY'),
    TRY_TO_DATE(ONBOARDING_DATE,'DD/MM/YYYY')
) IS NULL
;

SELECT DISTINCT RISK_TIER FROM RAW_MERCHANTS;
