SELECT TRANSACTION_ID 
FROM RAW_TRANSACTIONS
WHERE TRANSACTION_ID NOT LIKE 'T%'
OR TRANSACTION_ID IS NULL;

SELECT CUSTOMER_ID,ACCOUNT_ID 
FROM RAW_TRANSACTIONS
WHERE CUSTOMER_ID NOT LIKE 'C%'
OR ACCOUNT_ID NOT LIKE 'A%'
OR CUSTOMER_ID IS NULL
OR ACCOUNT_ID IS NULL;

SELECT 
    COALESCE(
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI')
    )
FROM RAW_TRANSACTIONS
WHERE  COALESCE(
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI')
    ) IS NOT NULL  ;


SELECT TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT,',',''),'£',''),'-','') AS FLOAT) AS AMOUNT
FROM RAW_TRANSACTIONS
WHERE TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT,',',''),'£',''),'-','') AS FLOAT) IS NOT NULL;

SELECT DISTINCT CURRENCY FROM RAW_TRANSACTIONS;

SELECT
    CASE 
          WHEN CURRENCY = 'GBP' THEN 1
          WHEN CURRENCY = 'USD' THEN 0.79
          WHEN CURRENCY = 'EUR' THEN 0.86
          WHEN CURRENCY = 'INR' THEN 0.0094
          WHEN CURRENCY = 'AED' THEN 0.215
    END AS FX_RATE_TO_GBP
FROM RAW_TRANSACTIONS
;

SELECT TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT_GBP,',',''),'£',''),'-','') AS FLOAT) AS AMOUNT_GBP
FROM RAW_TRANSACTIONS
WHERE TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT_GBP,',',''),'£',''),'-','') AS FLOAT) IS NOT NULL;

SELECT DISTINCT TRANSACTION_TYPE FROM RAW_TRANSACTIONS;

SELECT DISTINCT CHANNEL FROM RAW_TRANSACTIONS;

SELECT DISTINCT LOWER(merchant_category) AS merchant_category FROM RAW_TRANSACTIONS;

SELECT DISTINCT MERCHANT_CITY FROM RAW_TRANSACTIONS;

SELECT DISTINCT MERCHANT_COUNTRY FROM RAW_TRANSACTIONS;

SELECT DEVICE_ID,IP_ADDRESS FROM RAW_TRANSACTIONS;

SELECT DISTINCT LOWER(PAYMENT_METHOD) AS PAYMENT_METHOD FROM RAW_TRANSACTIONS;

SELECT DISTINCT LOWER(AUTHORIZATION_STATUS) FROM RAW_TRANSACTIONS;

SELECT DISTINCT LOWER(SETTLEMENT_STATUS) FROM RAW_TRANSACTIONS;

SELECT DISTINCT FRAUD_SCORE FROM RAW_TRANSACTIONS;

SELECT DISTINCT 
CASE 
    WHEN UPPER(TRIM(IS_INTERNATIONAL)) IN ('Y','YES','TRUE') THEN 'TRUE'
    WHEN UPPER(TRIM(IS_INTERNATIONAL)) IN ('N','NO','FALSE') THEN 'FALSE'
    ELSE 'UNKNOWN'
END AS IS_INTERNATIONAL
FROM RAW_TRANSACTIONS;

SELECT DISTINCT DECLINED_REASON FROM RAW_TRANSACTIONS;

SELECT MERCHANT_REFERENCE FROM RAW_TRANSACTIONS;
