select * from raw_cards;

-- CHECKING THE NULL VALUES AND INVALID FORMATE IN ACC ID AND CUST ID AND CARD ID
select CARD_ID,ACCOUNT_ID,CUSTOMER_ID from raw_cards
WHERE CARD_ID IS NULL OR ACCOUNT_ID IS NULL OR CUSTOMER_ID IS NULL
   OR CARD_ID NOT LIKE 'CRD%' OR ACCOUNT_ID NOT LIKE 'A%' OR CUSTOMER_ID NOT LIKE 'C%';

-- CHECKING THE UNIQUE VAUES IN CARD NETWORK
SELECT DISTINCT CARD_NETWORK
FROM RAW_CARDS;
 -- CHECKING THE NULL VALUES IN CARD NETWORK
SELECT CARD_NETWORK
FROM RAW_CARDS
WHERE CARD_NETWORK IS NULL;

-- CHECKING THE UNIQUE VALUES IN CARD TYPE
SELECT DISTINCT CARD_TYPE
FROM RAW_CARDS;


-- DATES
SELECT ISSUE_DATE FROM RAW_CARDS;
-- COUNT INVALID DATES
SELECT TRY_TO_DATE(ISSUE_DATE)
FROM RAW_CARDS;

SELECT COUNT(ISSUE_DATE)
FROM RAW_CARDS
WHERE TRY_TO_DATE(ISSUE_DATE) IS NULL;

-- CORRECTING DATES ✅
SELECT 
    COALESCE(
        TRY_TO_DATE(ISSUE_DATE,'DD-MM-YYYY'),
        TRY_TO_DATE(ISSUE_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(ISSUE_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(ISSUE_DATE,'YYYY/MM/DD')
    )
FROM RAW_CARDS;

-- CHECKING AFTER CORRECTING
SELECT ISSUE_DATE FROM RAW_CARDS
WHERE TRY_TO_DATE(ISSUE_DATE,'DD-MM-YYYY') IS NULL AND
        TRY_TO_DATE(ISSUE_DATE,'DD/MM/YYYY') IS NULL AND
        TRY_TO_DATE(ISSUE_DATE,'YYYY-MM-DD') IS NULL AND
        TRY_TO_DATE(ISSUE_DATE,'YYYY/MM/DD')IS NULL ;

select EXPIRY_DATE from raw_cards
WHERE EXPIRY_DATE NOT LIKE '%/%';

--CORRECTED EXP-DATE ✅ 
select 
CASE 
WHEN EXPIRY_DATE LIKE '%-%' THEN
    TO_VARCHAR(TRY_TO_DATE(EXPIRY_DATE,'YYYY-MM-DD'),'MM/YY')
ELSE
    EXPIRY_DATE
END 
from raw_cards
;



SELECT DISTINCT WALLET_TOKENIZED 
FROM RAW_CARDS;

--CORRECTED CARD STATUS ✅
SELECT DISTINCT LOWER(CARD_STATUS)  
FROM RAW_CARDS;


SELECT  WALLET_TOKENIZED,COUNT(*)
FROM RAW_CARDS
GROUP BY WALLET_TOKENIZED
HAVING COUNT(*) > 0
;


--CORRECTED WALLET TOKENIZED ✅
SELECT DISTINCT
CASE 
    WHEN WALLET_TOKENIZED IN ('No','N','false') THEN 'NO' 
    WHEN WALLET_TOKENIZED IN ('true','Yes','Y') THEN 'YES' 
    ELSE 'UNKNOWN'
END
FROM RAW_CARDS;

-- CORRECTED LAST 4
SELECT LPAD(TO_CHAR(LAST4),4,0) FROM RAW_CARDS;

SELECT DISTINCT COUNTRY_ISSUED FROM RAW_CARDS;
