SELECT DEVICE_ID
FROM RAW_DEVICES
WHERE DEVICE_ID IS NULL ;

SELECT CUSTOMER_ID_PRIMARY
FROM RAW_DEVICES
WHERE DEVICE_ID IS NULL ;

SELECT DISTINCT DEVICE_TYPE FROM RAW_DEVICES;

SELECT DISTINCT OS_NAME FROM RAW_DEVICES;

SELECT DISTINCT APP_VERSION FROM RAW_DEVICES;

-- CORRECTED TIME FOR BOTH FIRST AND LAST  ✅
SELECT TRY_TO_TIMESTAMP(FIRST_SEEN_TS) 
FROM RAW_DEVICES
WHERE TRY_TO_TIMESTAMP(FIRST_SEEN_TS) IS NULL;

SELECT TRY_TO_TIMESTAMP(LAST_SEEN_TS) 
FROM RAW_DEVICES
WHERE TRY_TO_TIMESTAMP(LAST_SEEN_TS) IS NULL;

-- CORRECTED JAILBROKE;
SELECT
CASE
    WHEN JAILBROKEN IN ('Y','Yes') THEN 'YES'
    WHEN JAILBROKEN IN ('N','No') THEN 'NO'
    ELSE 'UNKNOWN'
END AS JAILBROKEN
FROM RAW_DEVICES;

--CORRECTED VPN_USAGE
SELECT
CASE
    WHEN VPN_USAGE_FLAG IN ('Y','Yes') THEN 'YES'
    WHEN VPN_USAGE_FLAG IN ('N','No') THEN 'NO'
    ELSE 'UNKNOWN'
END AS VPN_USAGE_FLAG
FROM RAW_DEVICES;

-- CORRECTED HOME COUNTRY CODE
SELECT HOME_COUNTRY_CODE FROM RAW_DEVICES
