CREATE TABLE STG_MERCHANTS AS 
SELECT 
    MERCHANT_ID,
    REPLACE(MERCHANT_NAME,'*','') AS MERCHANT_NAME,
    MERCHANT_CATEGORY,
    CITY,
    COUNTRY,
    COALESCE(
        TRY_TO_DATE(ONBOARDING_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(ONBOARDING_DATE,'YYYY/MM/DD'),
        TRY_TO_DATE(ONBOARDING_DATE,'DD-MM-YYYY'),
        TRY_TO_DATE(ONBOARDING_DATE,'DD/MM/YYYY')
    ) AS ONBOARDING_DATE,
    RISK_TIER
FROM RAW_MERCHANTS;
