CREATE TABLE STG_DISPUTES AS 
SELECT 
    DISPUTE_ID,
    TRANSACTION_ID,
    CUSTOMER_ID,
    dispute_reason,
    LOWER(DISPUTE_STATUS) AS DISPUTE_STATUS,
    COALESCE(
    TRY_TO_DATE(OPENED_DATE,'YYYY-MM-DD'),
    TRY_TO_DATE(OPENED_DATE,'YYYY/MM/DD'),
    TRY_TO_DATE(OPENED_DATE,'DD-MM-YYYY'),
    TRY_TO_DATE(OPENED_DATE,'DD/MM/YYYY'),
    TRY_TO_DATE(OPENED_DATE,'DD-MON-YYYY'),
    TRY_TO_DATE(OPENED_DATE,'DD/MON/YYYY')
    ) AS OPENED_DATE,
    COALESCE(
    TRY_TO_DATE(CLOSED_DATE,'YYYY-MM-DD'),
    TRY_TO_DATE(CLOSED_DATE,'YYYY/MM/DD'),
    TRY_TO_DATE(CLOSED_DATE,'DD-MM-YYYY'),
    TRY_TO_DATE(CLOSED_DATE,'DD/MM/YYYY'),
    TRY_TO_DATE(CLOSED_DATE,'DD-MON-YYYY'),
    TRY_TO_DATE(CLOSED_DATE,'DD/MON/YYYY')
    ) AS CLOSED_DATE,
    TRY_CAST(REPLACE(DISPUTED_AMOUNT,'£','') AS FLOAT) AS DISPUTED_AMOUNT,
    TRY_CAST(REPLACE(RESOLUTION_AMOUNT,'£','') AS FLOAT) AS RESOLUTION_AMOUNT
FROM RAW_DISPUTES;
