CREATE TABLE STG_CARDS AS
SELECT 
        CARD_ID,CUSTOMER_ID,ACCOUNT_ID,CARD_NETWORK,CARD_TYPE,
        COALESCE(
        TRY_TO_DATE(ISSUE_DATE,'DD-MM-YYYY'),
        TRY_TO_DATE(ISSUE_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(ISSUE_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(ISSUE_DATE,'YYYY/MM/DD')
        ) AS ISSUE_DATE,
        CASE 
        WHEN EXPIRY_DATE LIKE '%-%' THEN
         TO_VARCHAR(TRY_TO_DATE(EXPIRY_DATE,'YYYY-MM-DD'),'MM/YY')
        ELSE
         EXPIRY_DATE
        END AS EXPIRY_DATE,
        LOWER(CARD_STATUS) AS CARD_STATUS,
        CASE 
            WHEN WALLET_TOKENIZED IN ('No','N','false') THEN 'NO' 
            WHEN WALLET_TOKENIZED IN ('true','Yes','Y') THEN 'YES' 
            ELSE 'UNKNOWN'
        END AS WALLET_TOKENIZED,
        LPAD(TO_CHAR(LAST4),4,0) AS LAST4,
        COUNTRY_ISSUED
FROM RAW_CARDS;
