CREATE TABLE STG_TRANSACTIONS AS 
SELECT 
    TRANSACTION_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    COALESCE(
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI')
    ) AS TRANSACTION_TS,
    TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT,',',''),'£',''),'-','') AS FLOAT) AS AMOUNT,
    CURRENCY,
    CASE 
          WHEN CURRENCY = 'GBP' THEN 1
          WHEN CURRENCY = 'USD' THEN 0.79
          WHEN CURRENCY = 'EUR' THEN 0.86
          WHEN CURRENCY = 'INR' THEN 0.0094
          WHEN CURRENCY = 'AED' THEN 0.215
    END AS FX_RATE_TO_GBP,
    TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT_GBP,',',''),'£',''),'-','') AS FLOAT) AS AMOUNT_GBP,
    TRANSACTION_TYPE,
    CHANNEL,
    LOWER(merchant_category) AS merchant_category,
    MERCHANT_CITY,
    MERCHANT_COUNTRY,
     DEVICE_ID,
     IP_ADDRESS,
     LOWER(PAYMENT_METHOD) AS PAYMENT_METHOD,
     LOWER(AUTHORIZATION_STATUS) AS AUTHORIZATION_STATUS,
     LOWER(SETTLEMENT_STATUS) AS SETTLEMENT_STATUS,
     FRAUD_SCORE,
     CASE 
        WHEN UPPER(TRIM(IS_INTERNATIONAL)) IN ('Y','YES','TRUE') THEN 'TRUE'
        WHEN UPPER(TRIM(IS_INTERNATIONAL)) IN ('N','NO','FALSE') THEN 'FALSE'
        ELSE 'UNKNOWN'
    END AS IS_INTERNATIONAL,
    DECLINED_REASON,
    MERCHANT_REFERENCE
FROM RAW_TRANSACTIONS
WHERE COALESCE(
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD-MM-YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'DD/MM/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-MM-DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/MM/DD HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY-DD-MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'YYYY/DD/MM HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM/DD/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI:SS'),
        TRY_TO_TIMESTAMP(TRANSACTION_TS,'MM-DD-YYYY HH24:MI')
    ) IS NOT NULL
    OR TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT,',',''),'£',''),'-','') AS FLOAT) IS NOT NULL
    OR TRY_CAST(REPLACE(REPLACE(REPLACE(AMOUNT_GBP,',',''),'£',''),'-','') AS FLOAT) IS NOT NULL;
    ;
