CREATE TABLE STG_CUSTOMERS AS
SELECT 
    CUSTOMER_ID,
    INITCAP(TRIM(FULL_NAME)) AS FULL_NAME,
    REPLACE(LOWER(TRIM(EMAIL)),' ','') AS EMAIL,
    LPAD(LPAD(PHONE,10,0),12,4) AS PHONE,
    COALESCE(
        TRY_TO_DATE(DATE_OF_BIRTH,'DD-MM-YYYY'),
        TRY_TO_DATE(DATE_OF_BIRTH,'DD/MM/YYYY'),
        TRY_TO_DATE(DATE_OF_BIRTH,'YYYY-MM-DD'),
        TRY_TO_DATE(DATE_OF_BIRTH,'YYYY/MM/DD')
        ) AS DATE_OF_BIRTH,
    COALESCE(
        TRY_TO_DATE(SIGNUP_DATE,'DD-MM-YYYY'),
        TRY_TO_DATE(SIGNUP_DATE,'DD/MM/YYYY'),
        TRY_TO_DATE(SIGNUP_DATE,'YYYY-MM-DD'),
        TRY_TO_DATE(SIGNUP_DATE,'YYYY/MM/DD')
        ) AS SIGNUP_DATE,
        CITY,
        COUNTRY,
        OCCUPATION,
        TRY_CAST(REPLACE(REPLACE(TRIM(ANNUAL_INCOME),',',''),'£','') AS FLOAT) AS ANNUAL_INCOME,
        LOWER(KYC_STATUS) AS KYC_STATUS,
        CASE 
            WHEN MARKETING_OPT_IN IN ('Y','Yes','true') THEN 'YES'
            WHEN MARKETING_OPT_IN IN ('N','No','false') THEN 'NO'
            ELSE 'NO'
        END AS MARKETING_OPT_IN,
        CASE 
            WHEN RISK_BAND IN ('Low','LOW') THEN 'Low'
            WHEN RISK_BAND IN ('med','Medium') THEN 'Medium'
            WHEN RISK_BAND IN ('High') THEN 'High'
            ELSE NULL
        END AS RISK_BAND,
        INITCAP(SEGMENT) AS SEGMENT,
        INITCAP(EMPLOYER_NAME) AS EMPLOYER_NAME
FROM RAW_CUSTOMERS;
